### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rodineicirineu** [opastorello/AliExpressPechincha#2]
Rapaz, instalei as dependências com pip e ao executar dá o seguinte erro:
[-] Erro: Não foi possivel carregar a página de login.
[!] Alerta: Ajudado 3 vezes.
Traceback (most recent call last):
  File "C:\Users\rodin\Downloads\AliExpressPechincha-main\AliExpressPechincha-main\app.py", line 31, in <module>
    saa = SeleniumAliAutomation(url)
  File "C:\Users\rodin\Downloads\AliExpressPechincha-main\AliExpressPechincha-main\saa.py", line 53, in __init__
    WebDriverWait(self.browser, 30).until(
  File "C:\Users\rodin\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 77, in until
    time.sleep(self._poll)
KeyboardInterrupt

**Comment by raphaelpinheiro84** [comment]
Estou com mesmo problema "erro ao abrir página de login"

**Comment by opastorello** [comment]
Não seria erro no código e sim algo em seu link, comenta a linha `firefox_options.set_headless()` e veja como o código esta se comportando.
